adding FAQ page
unitaryfoundation/unitaryhack2021 pull request #21
Opened 2021-04-16 05:01 UTC by crazy4pi314

Trying to answer some common questions!

2021-04-16 10:31 UTC, nathanshammah requested changes
Thanks @crazy4pi314, added some suggestions and comments.

2021-04-16 10:31 UTC, nathanshammah commented on faq.md
> +Hackers can make contributions anytime between May 14th and May 30th. Just be sure to [sign up here](https://7r2lxl70pvl.typeform.com/to/HfJLX5fl) and make sure that you put `[unitaryHACK]` in the ti
```suggestion
Hackers can make contributions anytime between May 14th and May 30th. Just be sure to [sign up here](https://airtable.com/embed/shrTG20PLC5cjVIPr) and make sure that you put `[unitaryHACK]` in the title of your pull request so the bots can find your contributions and make sure you get credit!
```

2021-04-16 10:31 UTC, nathanshammah commented on faq.md
> +You will find project built with a wide variety of languages like Python, Q#, Julia, Ruby, C++, and more.
```suggestion
You will find projects built with a wide variety of languages like Python, Q#, Julia, Ruby, C++, and more.
```

2021-04-16 10:31 UTC, nathanshammah commented on faq.md
> +There is a good mix between industry and applications focused projects as well as some that are more on the research side.
```suggestion
There is a good mix between industry-focused and application-focused projects as well as some that are more on the research side.
```

2021-04-16 10:31 UTC, nathanshammah commented on faq.md
> +There is a good mix between industry and applications focused projects as well as some that are more on the research side.
(I think)

2021-04-16 10:31 UTC, nathanshammah commented on faq.md
> +All times for the events will be in [PDT](https://time.is/PDT).
I wonder if the timezone point is really needed. To me it sounds a bit like discouraging for folks in other timezones, whereas the main message here I guess is that:
- times for deadlines, etc., are mainly PDT (but this can simply be added when needed)
- some interactive meetings, Q&As (Twitch, Discord, etc.) will be hosted at times suitable for folks in PDT. However, being the hack fully asynchronous, it relatively affects contributors. 

My vote is to omit it and just use PDT when expressing times.

2021-04-16 10:31 UTC, nathanshammah commented on faq.md
> +All skill levels can participate in unitaryHACK. We have worked with maintainers to make sure there are issues available for all levels of experience, both in quantum as well as open source contribut
```suggestion
Contributors with any skill level can participate in unitaryHACK. We have worked with maintainers to make sure there are issues available for all levels of experience, both for quantum-related as well as simply open-source-related contributions.
```

2021-04-16 10:31 UTC, nathanshammah commented on faq.md
> +**tl;dr**: Make a contribution to a [participating open source project](./participating-projects.md) between May 14-30th and you will win SWAG. Contribute a solution to a bountied issue and we will s
```suggestion
**tl;dr**: Make an approved contribution to a [participating open source project](./participating-projects.md) between May 14-30th and you will win SWAG. If your contribution to a bountied issue is deemed the satisfactory solution by the maintainers of the project, we will send you cash via PayPal.
```

2021-04-16 10:31 UTC, nathanshammah commented on faq.md
> +**tl;dr**: Make a contribution to a [participating open source project](./participating-projects.md) between May 14-30th and you will win SWAG. Contribute a solution to a bountied issue and we will s
Wanted to clarify this bit, as not simply opening a PR would qualify.

2021-04-16 10:31 UTC, nathanshammah commented on faq.md
> +Hackers can make contributions anytime between May 14th and May 30th. Just be sure to [sign up here](https://7r2lxl70pvl.typeform.com/to/HfJLX5fl) and make sure that you put `[unitaryHACK]` in the ti
Switched from the Typeform the Airtable link, which is the recently used one when one also clicks on "sign up" from the home page.

2021-04-20 04:11 UTC, crazy4pi314 commented
Thanks for the feedback @nathanshammah 💖 Will push live now for marketing tomorrow

2021-04-20 04:11 UTC, merged